
import React, { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import axios from "axios";

import { getExpectedExpenses } from "../../Services/AIService";
import { getCropById } from "../../Services/CropService";
import { getFarmById } from "../../Services/FarmService";

import "../../DisplayView.css";

const FarmCropExpense = () => {
    const navigate = useNavigate();
    const { cid } = useParams();

    const [report, setReport] = useState(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState("");

    useEffect(() => {
        const loadExpenseReport = async () => {
            try {
                if (!cid) {
                    throw new Error("Crop ID is missing.");
                }

                setLoading(true);
                setError("");

                console.log("Selected Crop ID:", cid);

                // =====================================================
                // 1. GET CROP DETAILS
                // =====================================================

                const cropResponse = await getCropById(cid);
                const crop = cropResponse.data;

                console.log("Crop Details:", crop);

                if (!crop) {
                    throw new Error("Crop details not found.");
                }

                // =====================================================
                // 2. GET FARM DETAILS
                // =====================================================

                const farmId =
                    crop.farmId ??
                    crop.farmID ??
                    crop.farm?.farmId ??
                    crop.farm?.id;

                let farm = null;

                if (farmId) {
                    const farmResponse = await getFarmById(farmId);
                    farm = farmResponse.data;

                    console.log("Farm Details:", farm);
                }

                // =====================================================
                // 3. GET RESOURCE QUANTITIES
                // =====================================================
                // AI is used ONLY for predicting required quantities.
                // AI rates are NOT used for expense calculation.

                const aiResponse = await getExpectedExpenses(cid);
                const ai = aiResponse.data;

                console.log("Predicted Resource Quantities:", ai);

                if (!ai) {
                    throw new Error(
                        "No resource prediction data received."
                    );
                }

                // =====================================================
                // 4. GET SAVED EXPENSE RATES
                // =====================================================
                // These values come from the database.
                // They are NOT generated by AI.

                const expenseResponse = await axios.get(
                    "http://localhost:9696/farmverse/agroexpense"
                );

                const expenseItems = expenseResponse.data;

                console.log(
                    "Saved Agro Expense Rates:",
                    expenseItems
                );

                if (
                    !Array.isArray(expenseItems) ||
                    expenseItems.length === 0
                ) {
                    throw new Error(
                        "No saved agro expense rates found in database."
                    );
                }

                // =====================================================
                // 5. GET RESOURCE QUANTITIES
                // =====================================================

                const water = Number(
                    ai.water ??
                    ai.waterGallon ??
                    0
                );

                const fertilizer = Number(
                    ai.fertilizer ?? 0
                );

                const pesticides = Number(
                    ai.pesticides ??
                    ai.pesticide ??
                    0
                );

                const tractorHour = Number(
    ai.tractorHour ?? 0
);

const agroTools = Number(
    ai.agroTools ??
    ai.agroTool ??
    ai.agroToolsRequired ??
    crop.cropArea ??
    0
);

                console.log("Resource Quantities:", {
                    water,
                    fertilizer,
                    pesticides,
                    tractorHour,
                    agroTools
                });

                // =====================================================
                // 6. FIND SAVED DATABASE RATE
                // =====================================================

                const getRate = (expenseName) => {
                    const expense = expenseItems.find((item) => {
                        const savedName = String(
                            item.expenseName ?? ""
                        )
                            .trim()
                            .toLowerCase();

                        return savedName ===
                            expenseName.trim().toLowerCase();
                    });

                    if (!expense) {
                        throw new Error(
                            `Saved rate not found for ${expenseName}.`
                        );
                    }

                    const rate = Number(
                        expense.ratePerUnit ?? 0
                    );

                    if (Number.isNaN(rate)) {
                        throw new Error(
                            `Invalid saved rate for ${expenseName}.`
                        );
                    }

                    return rate;
                };

                // =====================================================
                // 7. GET SAVED MENTOR RATES
                // =====================================================

                const waterRate =
                    getRate("waterGallon");

                const fertilizerRate =
                    getRate("fertilizer");

                const pesticidesRate =
                    getRate("pesticides");

                const tractorRate =
                    getRate("tractorHour");

                const agroToolsRate =
                    getRate("agroTools");

                console.log("DATABASE RATES:", {
                    waterRate,
                    fertilizerRate,
                    pesticidesRate,
                    tractorRate,
                    agroToolsRate
                });

                // =====================================================
                // 8. CALCULATE EXPENSE
                // =====================================================
                // Quantity = predicted resource requirement
                // Rate     = saved database/mentor rate

                const waterExp =
                    water * waterRate;

                const fertilizerExp =
                    fertilizer * fertilizerRate;

                const pesticidesExp =
                    pesticides * pesticidesRate;

                const tractorExp =
                    tractorHour * tractorRate;

                const agroToolsExp =
                    agroTools * agroToolsRate;

                const total =
                    waterExp +
                    fertilizerExp +
                    pesticidesExp +
                    tractorExp +
                    agroToolsExp;

                console.log("Expense Calculation:", {
                    waterExp,
                    fertilizerExp,
                    pesticidesExp,
                    tractorExp,
                    agroToolsExp,
                    total
                });

                // =====================================================
                // 9. FARM NAME
                // =====================================================

                const farmName =
                    farm?.farmName ??
                    farm?.name ??
                    farm?.farm_name ??
                    "-";

                // =====================================================
                // 10. CREATE FINAL REPORT
                // =====================================================

                const finalReport = {
                    cropId: cid,

                    cropName:
                        crop.cropName ??
                        ai.cropName ??
                        "-",

                    farmName,

                    soil:
                        crop.soil ??
                        crop.soilType ??
                        ai.soil ??
                        ai.soilType ??
                        "-",

                    cropArea:
                        crop.cropArea ??
                        ai.cropArea ??
                        "-",

                    sownMonthYear:
                        crop.sownMonthYear ??
                        ai.sownMonthYear ??
                        "-",

                    harvestMonthYear:
                        crop.harvestMonthYear ??
                        ai.harvestMonthYear ??
                        "-",

                    yield:
                        crop.yield ??
                        ai.yield ??
                        "-",

                    // Quantities
                    water,
                    fertilizer,
                    pesticides,
                    tractorHour,
                    agroTools,

                    // Saved rates
                    waterRate,
                    fertilizerRate,
                    pesticidesRate,
                    tractorRate,
                    agroToolsRate,

                    // Calculated expenses
                    waterExp,
                    fertilizerExp,
                    pesticidesExp,
                    tractorExp,
                    agroToolsExp,

                    total
                };

                console.log(
                    "FINAL EXPENSE REPORT:",
                    finalReport
                );

                setReport(finalReport);

            } catch (err) {
                console.error(
                    "Expense Report Error:",
                    err
                );

                if (err.response) {
                    console.error(
                        "HTTP Status:",
                        err.response.status
                    );

                    console.error(
                        "Server Response:",
                        err.response.data
                    );
                }

                setError(
                    err.message ||
                    "Unable to load expense report."
                );

            } finally {
                setLoading(false);
            }
        };

        loadExpenseReport();

    }, [cid]);

    // =========================================================
    // BACK
    // =========================================================

    const handleBack = () => {
        navigate("/crop-list");
    };

    // =========================================================
    // LOADING
    // =========================================================

    if (loading) {
        return (
            <div className="list-page">
                <div className="page-banner">
                    <h1>💰 Crop Expense Report</h1>
                    <p>
                        Loading expense calculation...
                    </p>
                </div>
            </div>
        );
    }

    // =========================================================
    // ERROR
    // =========================================================

    if (error) {
        return (
            <div className="list-page">

                <div className="page-banner">
                    <h1>❌ Expense Report Failed</h1>

                    <p>{error}</p>
                </div>

                <div className="return-btn-container">
                    <button
                        className="return-btn"
                        onClick={handleBack}
                    >
                        ← Return to Crop List
                    </button>
                </div>

            </div>
        );
    }

    // =========================================================
    // NO REPORT
    // =========================================================

    if (!report) {
        return (
            <div className="list-page">

                <div className="page-banner">
                    <h1>⚠️ No Expense Data</h1>

                    <p>
                        No expense data available.
                    </p>
                </div>

                <div className="return-btn-container">
                    <button
                        className="return-btn"
                        onClick={handleBack}
                    >
                        ← Return to Crop List
                    </button>
                </div>

            </div>
        );
    }

    // =========================================================
    // DISPLAY REPORT
    // =========================================================

    return (
        <div className="list-page">

            <div className="page-banner">

                <h1>
                    💰 Crop Expense Report
                </h1>

                <p>
                    Detailed resource requirements and
                    expense calculation
                </p>

            </div>

            <div className="list-card">

                {/* =================================================
                    CROP DETAILS
                ================================================= */}

                <h2 className="list-title">
                    🌱 Crop Details
                </h2>

                <table className="list-table">

                    <tbody>

                        <tr>
                            <th>Crop ID</th>
                            <td>{report.cropId}</td>
                        </tr>

                        <tr>
                            <th>Crop Name</th>
                            <td>{report.cropName}</td>
                        </tr>

                        <tr>
                            <th>Farm Name</th>
                            <td>{report.farmName}</td>
                        </tr>

                        <tr>
                            <th>Soil Type</th>
                            <td>{report.soil}</td>
                        </tr>

                        <tr>
                            <th>Crop Area</th>
                            <td>
                                {report.cropArea} Acres
                            </td>
                        </tr>

                        <tr>
                            <th>Sown Month / Year</th>
                            <td>
                                {report.sownMonthYear}
                            </td>
                        </tr>

                        <tr>
                            <th>Harvest Month / Year</th>
                            <td>
                                {report.harvestMonthYear}
                            </td>
                        </tr>

                        <tr>
                            <th>Expected Yield</th>
                            <td>{report.yield}</td>
                        </tr>

                    </tbody>

                </table>

                {/* =================================================
                    EXPENSE TABLE
                ================================================= */}

               <h2
    className="list-title"
    style={{
        marginTop: "30px"
    }}
>
    📊 Resource Requirements & Cost Analysis
</h2>

<table className="list-table">

    <thead>
        <tr>
            <th>Resource</th>
            <th>Required Quantity</th>
            <th>Total Expense</th>
        </tr>
    </thead>

    <tbody>

        <tr>
            <td>💧 Water</td>

            <td>
                {report.water} Gallons
            </td>

            <td>
                ₹ {report.waterExp.toFixed(2)}
            </td>
        </tr>

        <tr>
            <td>🌿 Fertilizer</td>

            <td>
                {report.fertilizer} kg
            </td>

            <td>
                ₹ {report.fertilizerExp.toFixed(2)}
            </td>
        </tr>

        <tr>
            <td>🧪 Pesticides</td>

            <td>
                {report.pesticides} kg
            </td>

            <td>
                ₹ {report.pesticidesExp.toFixed(2)}
            </td>
        </tr>

        <tr>
            <td>🚜 Tractor Usage</td>

            <td>
                {report.tractorHour} Hours
            </td>

            <td>
                ₹ {report.tractorExp.toFixed(2)}
            </td>
        </tr>

        <tr>
            <td>🛠️ Agro Tools</td>

            <td>
                {report.agroTools} Units
            </td>

            <td>
                ₹ {report.agroToolsExp.toFixed(2)}
            </td>
        </tr>

    </tbody>

</table>

                {/* =================================================
                    TOTAL
                ================================================= */}

                <div
                    className="total-expense"
                    style={{
                        marginTop: "25px",
                        padding: "20px",
                        textAlign: "center",
                        fontSize: "22px",
                        fontWeight: "bold"
                    }}
                >
                    💰 Total Crop Expense: ₹{" "}
                    {report.total.toFixed(2)}
                </div>

                {/* =================================================
                    BACK BUTTON
                ================================================= */}

                <div className="return-btn-container">

                    <button
                        className="return-btn"
                        onClick={handleBack}
                    >
                        ← Return to Crop List
                    </button>

                </div>

            </div>

        </div>
    );
};

export default FarmCropExpense;

